services:
  app:
    build: .
    ports:
      - "9999:9999"
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_KEY=${TWILIO_KEY}
    volumes:
      - .:/app
